name: Build and Release App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to create releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Auto-increment Version and Tag
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          npm version 1.0.${{ github.run_number }} --no-git-tag-version
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
