name: Build and Release App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to create releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Auto-increment Version
        run: npm version 1.0.${{ github.run_number }} --no-git-tag-version

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
